repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9  # frozen: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --indent, "4", "--top-keys", "$schema,extends"]
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 60cc33571a98248f908ee4771a45b82951f52c62  # frozen: 35.53.0
    hooks:
      - id: renovate-config-validator
        files: \.json$
